services:
  - type: web
    name: squad-up-web
    env: php
    buildCommand: "composer install --no-dev --optimize-autoloader"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    plan: free
    region: frankfurt
